--- Makefile	2008-05-11 14:30:54.000000000 -0700
+++ Makefile	2008-09-24 16:23:27.225400200 -0700
@@ -31,13 +31,14 @@
 TOP_BUILDDIR=$(shell pwd)
 include .paths
 
-SUBDIRS=libddbg libparam diskmodel memsmodel src
+SUBDIRS=libddbg libparam diskmodel memsmodel ssdmodel src
 
 all: 	
 	$(MAKE) -C libddbg
 	$(MAKE) -C libparam
 	$(MAKE) -C diskmodel
 	$(MAKE) -C memsmodel
+	$(MAKE) -C ssdmodel
 	$(MAKE) -C src
 	$(MAKE) -C diskmodel/layout_g4_tools
         # If dixtrac is included, build it with the distribution
@@ -61,10 +62,12 @@
 	$(MAKE) -C src/modules
 	$(MAKE) -C diskmodel/modules
 	$(MAKE) -C memsmodel/modules
+	$(MAKE) -C ssdmodel/modules
 
 doc-clean:
 	$(MAKE) -C memsmodel/modules distclean
 	$(MAKE) -C diskmodel/modules distclean
+	$(MAKE) -C ssdmodel/modules distclean
 	$(MAKE) -C src/modules distclean
 	$(MAKE) -C libparam distclean
 	$(MAKE) -C libddbg distclean
